---
- hosts: localhost
  become: True
  connection: local
  vars_files:
   - jobs.yml
  tasks:
      - package: name={{item}}
        with_items:
          - python3
          - jq
          - python3-pip
          - java-1.8.0-openjdk
          - gcc
      - pip: name=jenkins-job-builder state=latest executable=/usr/bin/pip3          
#       - pip: name={{item}} state=latest executable=/usr/bin/pip3
#         with_items:
#           - yamllint
#           - jenkins-job-builder
      - file:
          path: /etc/jenkins_jobs/{{ item }}
          state: directory
        with_items:
          - jobs
          - config
      - file:
          path: /opt/jenkins/
          state: directory
          owner: ec2-user
          group: ec2-user
      - copy:
          src: ./files/{{ item }}
          dest: /opt/jenkins/{{ item }}
          owner: ec2-user
          group: ec2-user
        with_items:
          - add_admin.groovy
          - Dockerfile
          - docker-compose.yml
      - template: src="./templates/jenkins_jobs.ini.tmp" dest="/etc/jenkins_jobs/jenkins_jobs.ini" mode=0600 owner="ec2-user"
        with_items: "{{ jobs }}"
      - template: src="./templates/jenkins_job.tmp" dest="/etc/jenkins_jobs/jobs/{{item.name}}.yml" mode=0600 owner="ec2-user"
        with_items: "{{ jobs }}"
      - name: Install docker-compose
        get_url:
          url : https://github.com/docker/compose/releases/download/1.27.3/docker-compose-Linux-x86_64
          dest: /usr/local/bin/docker-compose
          mode: 'u+x,g+x'
      - command: /usr/local/bin/docker-compose build
        args:
         chdir: /opt/jenkins/
      - command: /usr/local/bin/docker-compose up -d
        args:
         chdir: /opt/jenkins/
      - command: /usr/local/bin/jenkins-jobs update {{item}}
        with_fileglob:
          - /etc/jenkins_jobs/jobs/*.yml
        register: output
      - debug: var=output
