version: '2'
services:
  jenkins:
    image: scalr-demo:latest
    container_name: jenkins
    user: jenkins
    volumes:
      - /opt/jenkins/:/var/jenkins_home
      - /opt/jenkins/var/run/docker.sock:/var/run/docker.sock
      - /etc/jenkins_jobs/:/etc/jenkins_jobs
    environment:
      JAVA_OPTS: "-Dhudson.Main.development=true -Djenkins.install.runSetupWizard=false"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
